# Generated by Django 3.1.2 on 2020-10-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201018_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='title',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='title',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
